export const MOCK_CELLS = [
  {
    id: 'JES-01',
    name: 'Jesolo Centro',
    area: 'Jesolo',
    sector: 'Centro Storico',
    lat: 45.5047,
    lng: 12.6447,
    status: 'active',
    technology: 'WiFi',
    lastReading: {
      Temperature: 22.4,
      Humidity: 58.1,
      CO2: 612,
      PM25: 8.3,
      PM10: 14.1,
      IndoorAirQuality: 74,
      IndoorAirQualityInterpreted: 'Buona',
      MarkerDate: new Date().toISOString(),
    },
  },
  {
    id: 'JES-02',
    name: 'Jesolo Lungomare',
    area: 'Jesolo',
    sector: 'Lungomare',
    lat: 45.5080,
    lng: 12.6600,
    status: 'active',
    technology: 'WiFi',
    lastReading: {
      Temperature: 23.1,
      Humidity: 62.5,
      CO2: 480,
      PM25: 5.1,
      PM10: 9.2,
      IndoorAirQuality: 42,
      IndoorAirQualityInterpreted: 'Eccellente',
      MarkerDate: new Date().toISOString(),
    },
  },
  {
    id: 'JES-03',
    name: 'Jesolo Entroterra',
    area: 'Jesolo',
    sector: 'Entroterra',
    lat: 45.5000,
    lng: 12.6300,
    status: 'warning',
    technology: 'LoRa P2P',
    lastReading: {
      Temperature: 19.8,
      Humidity: 71.2,
      CO2: 980,
      PM25: 22.4,
      PM10: 38.1,
      IndoorAirQuality: 165,
      IndoorAirQualityInterpreted: 'Scarsa',
      MarkerDate: new Date().toISOString(),
    },
  },
  {
    id: 'CGN-01',
    name: 'Conegliano Centro',
    area: 'Conegliano',
    sector: 'Centro',
    lat: 45.8887,
    lng: 12.2983,
    status: 'active',
    technology: 'WiFi+LoRa',
    lastReading: {
      Temperature: 17.3,
      Humidity: 55.8,
      CO2: 520,
      PM25: 6.7,
      PM10: 11.4,
      IndoorAirQuality: 58,
      IndoorAirQualityInterpreted: 'Buona',
      MarkerDate: new Date().toISOString(),
    },
  },
  {
    id: 'MES-01',
    name: 'Mestre Stazione',
    area: 'Mestre',
    sector: 'Zona Stazione',
    lat: 45.4920,
    lng: 12.2387,
    status: 'active',
    technology: 'WiFi',
    lastReading: {
      Temperature: 20.5,
      Humidity: 49.3,
      CO2: 1240,
      PM25: 31.2,
      PM10: 52.8,
      IndoorAirQuality: 188,
      IndoorAirQualityInterpreted: 'Scarsa',
      MarkerDate: new Date().toISOString(),
    },
  },
  {
    id: 'GAV-01',
    name: 'Gavaz Belluno',
    area: 'Gavaz',
    sector: 'Montagna',
    lat: 46.1370,
    lng: 12.2170,
    status: 'active',
    technology: 'LoRa P2P',
    lastReading: {
      Temperature: 11.2,
      Humidity: 44.6,
      CO2: 410,
      PM25: 2.1,
      PM10: 4.3,
      IndoorAirQuality: 31,
      IndoorAirQualityInterpreted: 'Eccellente',
      MarkerDate: new Date().toISOString(),
    },
  },
]
